export const HEADER_TEAM: Array<
  Record<
    "id" | "title" | "url" | "description" | "function" | "position",
    string
  >
> = [
  {
    id: crypto.randomUUID(),
    title: "Ban Game",
    url: "game",
    description: "Đội ngũ game",
    function: "Khối giải trí",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Game",
    url: "game",
    description: "Đội ngũ game",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Game",
    url: "game",
    description: "Đội ngũ game",
    function: "Khối giải trí",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban App - Desktop",
    url: "app-desktop",
    description: "Đội ngũ ứng dụng máy tính",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban App - Desktop",
    url: "app-desktop",
    description: "Đội ngũ ứng dụng máy tính",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban App - Desktop",
    url: "app-desktop",
    description: "Đội ngũ ứng dụng máy tính",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban App - Embedded",
    url: "app-embedded",
    description: "Đội ngũ ứng dụng nhúng",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban App - Embedded",
    url: "app-embedded",
    description: "Đội ngũ ứng dụng nhúng",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban App - Embedded",
    url: "app-embedded",
    description: "Đội ngũ ứng dụng nhúng",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - Frontend",
    url: "web-frontend",
    description: "Đội ngũ ứng dụng web - Frontend",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - Frontend",
    url: "web-frontend",
    description: "Đội ngũ ứng dụng web - Frontend",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - Frontend",
    url: "web-frontend",
    description: "Đội ngũ ứng dụng web - Frontend",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - Backend",
    url: "web-backend",
    description: "Đội ngũ ứng dụng web - Backend",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - Backend",
    url: "web-backend",
    description: "Đội ngũ ứng dụng web - Backend",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - Backend",
    url: "web-backend",
    description: "Đội ngũ ứng dụng web - Backend",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - UI/UX",
    url: "web-uiux",
    description: "Đội ngũ ứng dụng web - UI/UX",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - UI/UX",
    url: "web-uiux",
    description: "Đội ngũ ứng dụng web - UI/UX",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Web - UI/UX",
    url: "web-uiux",
    description: "Đội ngũ ứng dụng web - UI/UX",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - ML",
    url: "ai-ml",
    description: "Đội ngũ AI - Machine Learning",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - ML",
    url: "ai-ml",
    description: "Đội ngũ AI - Machine Learning",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - ML",
    url: "ai-ml",
    description: "Đội ngũ AI - Machine Learning",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - CV",
    url: "ai-cv",
    description: "Đội ngũ AI - Computer Vision",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - CV",
    url: "ai-cv",
    description: "Đội ngũ AI - Computer Vision",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - CV",
    url: "ai-cv",
    description: "Đội ngũ AI - Computer Vision",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - NLP",
    url: "ai-nlp",
    description: "Đội ngũ AI - Natural Language Processing",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - NLP",
    url: "ai-nlp",
    description: "Đội ngũ AI - Natural Language Processing",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban AI - NLP",
    url: "ai-nlp",
    description: "Đội ngũ AI - Natural Language Processing",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Cybersec - Web",
    url: "cybersec-web",
    description: "Đội ngũ Cybersecurity - Web",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Cybersec - Web",
    url: "cybersec-web",
    description: "Đội ngũ Cybersecurity - Web",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Cybersec - Web",
    url: "cybersec-web",
    description: "Đội ngũ Cybersecurity - Web",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Cybersec - App",
    url: "cybersec-app",
    description: "Đội ngũ Cybersecurity - App",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Cybersec - App",
    url: "cybersec-app",
    description: "Đội ngũ Cybersecurity - App",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Cybersec - App",
    url: "cybersec-app",
    description: "Đội ngũ Cybersecurity - App",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Marketing and Economy",
    url: "marketing-economy",
    description: "Đội ngũ Marketing and Economy",
    function: "Khối công nghệ",
    position: "Trưởng ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Marketing and Economy",
    url: "marketing-economy",
    description: "Đội ngũ Marketing and Economy",
    function: "Khối công nghệ",
    position: "Phó ban",
  },
  {
    id: crypto.randomUUID(),
    title: "Ban Marketing and Economy",
    url: "marketing-economy",
    description: "Đội ngũ Marketing and Economy",
    function: "Khối công nghệ",
    position: "Thành viên",
  },
  // {
  //   id: crypto.randomUUID(),
  //   title: "Ban Quét sân",
  //   url: "quet_san",
  //   description: "Đội ngũ quét sân trường",
  //   function: "Khối lao động công ích",
  //   position: "Thành viên",
  // },
  // {
  //   id: crypto.randomUUID(),
  //   title: "Ban Vệ sinh",
  //   url: "ve_sinh",
  //   description: "Đội ngũ vệ sinh lớp học",
  //   function: "Khối lao động công ích",
  //   position: "Thành viên",
  // },
  // {
  //   id: crypto.randomUUID(),
  //   title: "Ban Thực phẩm",
  //   url: "thuc_pham",
  //   description: "Đội ngũ thực phẩm",
  //   function: "Khối lao động công ích",
  //   position: "Thành viên",
  // },
  // {
  //   id: crypto.randomUUID(),
  //   title: "Ban Không khí",
  //   url: "khong_khi",
  //   description: "Đội ngũ không khí",
  //   function: "Khối lao động công ích",
  //   position: "Thành viên",
  // },
];

export const NAVIGATION_MENU: Array<{
  id: string;
  title: string;
  url: string;
}> = [
  {
    id: crypto.randomUUID(),
    title: "Trang chủ",
    url: "/",
  },
  {
    id: crypto.randomUUID(),
    title: "Tuyển thành viên",
    url: "/job-openings",
  },
];
